name: Build and Deploy Code

on: [push, pull_request] #event to trigger the job/workflow

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling from repo
        uses: actions/checkout@v4
      - name: say hi
        run: echo "Hi Adarsh"  # linux command
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: installing requirements
        run: pip install -r requirements.txt
      - name: run tests with pytest
        run: |
          pip install pytest
          pytest